{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mJupyter server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31m/home/halil/.local/lib/python3.12/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/home/halil/Belgeler/Kodlama calismalari/py/Patika' instead of '\"/home/halil/Belgeler/Kodlama calismalari/py/Patika\"' if you require traitlets >=5.\n",
      "\u001b[1;31m  warn(\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[I 15:30:37.256 NotebookApp] Loading IPython parallel extension\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[I 15:30:37.262 NotebookApp] The port 8888 is already in use, trying another port.\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/bin/jupyter-notebook\", line 8, in <module>\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    \n",
      "\u001b[1;31msys.exit(main())\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m \n",
      "\u001b[1;31m \n",
      "\u001b[1;31m \n",
      "\u001b[1;31m \n",
      "\u001b[1;31m \n",
      "\u001b[1;31m \n",
      "\u001b[1;31m \n",
      "\u001b[1;31m \n",
      "\u001b[1;31m \n",
      "\u001b[1;31m \n",
      "\u001b[1;31m \n",
      "\u001b[1;31m \n",
      "\u001b[1;31m \n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/jupyter_core/application.py\", line 277, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    \n",
      "\u001b[1;31mreturn super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m \n",
      "\u001b[1;31m \n",
      "\u001b[1;31m \n",
      "\u001b[1;31m \n",
      "\u001b[1;31m \n",
      "\u001b[1;31m \n",
      "\u001b[1;31m \n",
      "\u001b[1;31m \n",
      "\u001b[1;31m \n",
      "\u001b[1;31m \n",
      "\u001b[1;31m \n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "\u001b[1;31m    app.start()\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 2320, in start\n",
      "\u001b[1;31m    success = self._bind_http_server()\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1795, in _bind_http_server\n",
      "\u001b[1;31m    return self._bind_http_server_unix() if self.sock else self._bind_http_server_tcp()\n",
      "\u001b[1;31m                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1821, in _bind_http_server_tcp\n",
      "\u001b[1;31m    self.http_server.listen(port, self.ip)\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 191, in listen\n",
      "\u001b[1;31m    self.add_sockets(sockets)\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 204, in add_sockets\n",
      "\u001b[1;31m    self._handlers[sock.fileno()] = add_accept_handler(\n",
      "\u001b[1;31m                                    ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/netutil.py\", line 247, in add_accept_handler\n",
      "\u001b[1;31m    io_loop = IOLoop.current()\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/ioloop.py\", line 265, in current\n",
      "\u001b[1;31m    loop = asyncio.get_event_loop()\n",
      "\u001b[1;31m           ^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/nest_asyncio.py\", line 45, in _get_event_loop\n",
      "\u001b[1;31m    loop = events.get_event_loop_policy().get_event_loop()\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/usr/local/lib/python3.12/asyncio/events.py\", line 676, in get_event_loop\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    raise RuntimeError('There is no current event loop in thread %r.'\n",
      "\u001b[1;31mRuntimeError: There is no current event loop in thread 'MainThread'. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import math\n",
    "import matplotlib as plt\n",
    "from pandas.api.types import is_string_dtype,is_numeric_dtype\n",
    "\n",
    "%matplotlib inline"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mJupyter server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31m/home/halil/.local/lib/python3.12/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science' instead of '\"/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science\"' if you require traitlets >=5.\n",
      "\u001b[1;31m  warn(\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[I 15:13:06.082 NotebookApp] Loading IPython parallel extension\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/home/halil/.local/bin/jupyter-notebook\", line 8, in <module>\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    sys.exit(main())\n",
      "\u001b[1;31m             ^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/jupyter_core/application.py\", line 277, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    app.start()\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 2320, in start\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    success = self._bind_http_server()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1795, in _bind_http_server\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return self._bind_http_server_unix() if self.sock else self._bind_http_server_tcp()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m                                                           ^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1821, in _bind_http_server_tcp\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    self.http_server.listen(port, self.ip)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 191, in listen\n",
      "\u001b[1;31m    self.add_sockets(sockets)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 204, in add_sockets\n",
      "\u001b[1;31m    self._handlers[sock.fileno()] = add_accept_handler(\n",
      "\u001b[1;31m      \n",
      "\u001b[1;31m                              ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/netutil.py\", line 247, in add_accept_handler\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    io_loop = IOLoop.current()\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/ioloop.py\", line 265, in current\n",
      "\u001b[1;31m    loop = asyncio.get_event_loop()\n",
      "\u001b[1;31m           ^^^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/nest_asyncio.py\", line 45, in _get_event_loop\n",
      "\u001b[1;31m    loop = events.get_event_loop_policy().get_event_loop()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/usr/local/lib/python3.12/asyncio/events.py\", line 676, in get_event_loop\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    raise RuntimeError('There is no current event loop in thread %r.'\n",
      "\u001b[1;31mRuntimeError: There is no current event loop in thread 'MainThread'. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "PATH = '/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science/data/bulldozers/' \n",
    "\n",
    "df=pd.read_csv(f'{PATH}Train.csv',low_memory=False,parse_dates=[\"saledate\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mJupyter server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31m/home/halil/.local/lib/python3.12/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science' instead of '\"/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science\"' if you require traitlets >=5.\n",
      "\u001b[1;31m  warn(\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[I 15:13:06.082 NotebookApp] Loading IPython parallel extension\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/home/halil/.local/bin/jupyter-notebook\", line 8, in <module>\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    sys.exit(main())\n",
      "\u001b[1;31m             ^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/jupyter_core/application.py\", line 277, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    app.start()\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 2320, in start\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    success = self._bind_http_server()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1795, in _bind_http_server\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return self._bind_http_server_unix() if self.sock else self._bind_http_server_tcp()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m                                                           ^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1821, in _bind_http_server_tcp\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    self.http_server.listen(port, self.ip)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 191, in listen\n",
      "\u001b[1;31m    self.add_sockets(sockets)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 204, in add_sockets\n",
      "\u001b[1;31m    self._handlers[sock.fileno()] = add_accept_handler(\n",
      "\u001b[1;31m      \n",
      "\u001b[1;31m                              ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/netutil.py\", line 247, in add_accept_handler\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    io_loop = IOLoop.current()\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/ioloop.py\", line 265, in current\n",
      "\u001b[1;31m    loop = asyncio.get_event_loop()\n",
      "\u001b[1;31m           ^^^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/nest_asyncio.py\", line 45, in _get_event_loop\n",
      "\u001b[1;31m    loop = events.get_event_loop_policy().get_event_loop()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/usr/local/lib/python3.12/asyncio/events.py\", line 676, in get_event_loop\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    raise RuntimeError('There is no current event loop in thread %r.'\n",
      "\u001b[1;31mRuntimeError: There is no current event loop in thread 'MainThread'. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "df.head()"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## RMSLE"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mJupyter server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31m/home/halil/.local/lib/python3.12/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science' instead of '\"/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science\"' if you require traitlets >=5.\n",
      "\u001b[1;31m  warn(\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[I 15:13:06.082 NotebookApp] Loading IPython parallel extension\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/home/halil/.local/bin/jupyter-notebook\", line 8, in <module>\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    sys.exit(main())\n",
      "\u001b[1;31m             ^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/jupyter_core/application.py\", line 277, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    app.start()\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 2320, in start\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    success = self._bind_http_server()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1795, in _bind_http_server\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return self._bind_http_server_unix() if self.sock else self._bind_http_server_tcp()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m                                                           ^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1821, in _bind_http_server_tcp\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    self.http_server.listen(port, self.ip)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 191, in listen\n",
      "\u001b[1;31m    self.add_sockets(sockets)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 204, in add_sockets\n",
      "\u001b[1;31m    self._handlers[sock.fileno()] = add_accept_handler(\n",
      "\u001b[1;31m      \n",
      "\u001b[1;31m                              ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/netutil.py\", line 247, in add_accept_handler\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    io_loop = IOLoop.current()\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/ioloop.py\", line 265, in current\n",
      "\u001b[1;31m    loop = asyncio.get_event_loop()\n",
      "\u001b[1;31m           ^^^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/nest_asyncio.py\", line 45, in _get_event_loop\n",
      "\u001b[1;31m    loop = events.get_event_loop_policy().get_event_loop()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/usr/local/lib/python3.12/asyncio/events.py\", line 676, in get_event_loop\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    raise RuntimeError('There is no current event loop in thread %r.'\n",
      "\u001b[1;31mRuntimeError: There is no current event loop in thread 'MainThread'. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "df['SalePriceLog'] = np.log(df.SalePrice)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mJupyter server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31m/home/halil/.local/lib/python3.12/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science' instead of '\"/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science\"' if you require traitlets >=5.\n",
      "\u001b[1;31m  warn(\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[I 15:13:06.082 NotebookApp] Loading IPython parallel extension\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/home/halil/.local/bin/jupyter-notebook\", line 8, in <module>\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    sys.exit(main())\n",
      "\u001b[1;31m             ^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/jupyter_core/application.py\", line 277, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    app.start()\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 2320, in start\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    success = self._bind_http_server()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1795, in _bind_http_server\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return self._bind_http_server_unix() if self.sock else self._bind_http_server_tcp()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m                                                           ^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1821, in _bind_http_server_tcp\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    self.http_server.listen(port, self.ip)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 191, in listen\n",
      "\u001b[1;31m    self.add_sockets(sockets)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 204, in add_sockets\n",
      "\u001b[1;31m    self._handlers[sock.fileno()] = add_accept_handler(\n",
      "\u001b[1;31m      \n",
      "\u001b[1;31m                              ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/netutil.py\", line 247, in add_accept_handler\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    io_loop = IOLoop.current()\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/ioloop.py\", line 265, in current\n",
      "\u001b[1;31m    loop = asyncio.get_event_loop()\n",
      "\u001b[1;31m           ^^^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/nest_asyncio.py\", line 45, in _get_event_loop\n",
      "\u001b[1;31m    loop = events.get_event_loop_policy().get_event_loop()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/usr/local/lib/python3.12/asyncio/events.py\", line 676, in get_event_loop\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    raise RuntimeError('There is no current event loop in thread %r.'\n",
      "\u001b[1;31mRuntimeError: There is no current event loop in thread 'MainThread'. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "df[['SalePrice','SalePriceLog']].head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mJupyter server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31m/home/halil/.local/lib/python3.12/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science' instead of '\"/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science\"' if you require traitlets >=5.\n",
      "\u001b[1;31m  warn(\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[I 15:13:06.082 NotebookApp] Loading IPython parallel extension\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/home/halil/.local/bin/jupyter-notebook\", line 8, in <module>\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    sys.exit(main())\n",
      "\u001b[1;31m             ^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/jupyter_core/application.py\", line 277, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    app.start()\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 2320, in start\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    success = self._bind_http_server()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1795, in _bind_http_server\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return self._bind_http_server_unix() if self.sock else self._bind_http_server_tcp()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m                                                           ^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1821, in _bind_http_server_tcp\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    self.http_server.listen(port, self.ip)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 191, in listen\n",
      "\u001b[1;31m    self.add_sockets(sockets)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 204, in add_sockets\n",
      "\u001b[1;31m    self._handlers[sock.fileno()] = add_accept_handler(\n",
      "\u001b[1;31m      \n",
      "\u001b[1;31m                              ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/netutil.py\", line 247, in add_accept_handler\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    io_loop = IOLoop.current()\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/ioloop.py\", line 265, in current\n",
      "\u001b[1;31m    loop = asyncio.get_event_loop()\n",
      "\u001b[1;31m           ^^^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/nest_asyncio.py\", line 45, in _get_event_loop\n",
      "\u001b[1;31m    loop = events.get_event_loop_policy().get_event_loop()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/usr/local/lib/python3.12/asyncio/events.py\", line 676, in get_event_loop\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    raise RuntimeError('There is no current event loop in thread %r.'\n",
      "\u001b[1;31mRuntimeError: There is no current event loop in thread 'MainThread'. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "df[\"UsageBand\"]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mJupyter server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31m/home/halil/.local/lib/python3.12/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science' instead of '\"/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science\"' if you require traitlets >=5.\n",
      "\u001b[1;31m  warn(\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[I 15:34:58.784 NotebookApp] Loading IPython parallel extension\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[I 15:34:58.787 NotebookApp] The port 8888 is already in use, trying another port.\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/home/halil/.local/bin/jupyter-notebook\", line 8, in <module>\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    sys.exit(main())\n",
      "\u001b[1;31m             ^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/jupyter_core/application.py\", line 277, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    app.start()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 2320, in start\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    success = self._bind_http_server()\n",
      "\u001b[1;31m  \n",
      "\u001b[1;31m            ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1795, in _bind_http_server\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return self._bind_http_server_unix() if self.sock else self._bind_http_server_tcp()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m                                                         \n",
      "\u001b[1;31m  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1821, in _bind_http_server_tcp\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    self.http_server.listen(port, self.ip)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 191, in listen\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    self.add_sockets(sockets)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 204, in add_sockets\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    self._handlers[sock.fileno()] = add_accept_handler(\n",
      "\u001b[1;31m          \n",
      "\u001b[1;31m                          ^^^^^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/netutil.py\", line 247, in add_accept_handler\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    io_loop = IOLoop.current()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^\n",
      "\u001b[1;31m^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/ioloop.py\", line 265, in current\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    loop = asyncio.get_event_loop()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/nest_asyncio.py\", line 45, in _get_event_loop\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    loop = events.get_event_loop_policy().get_event_loop()\n",
      "\u001b[1;31m          \n",
      "\u001b[1;31m ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/usr/local/lib/python3.12/asyncio/events.py\", line 676, in get_event_loop\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    raise RuntimeError('There is no current event loop in thread %r.'\n",
      "\u001b[1;31mRuntimeError: There is no current event loop in thread 'MainThread'. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "for n,c in df.items():\n",
    "    print(n)\n",
    "    print(\"----------\")\n",
    "    print(c)\n",
    "    break"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mJupyter server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31m/home/halil/.local/lib/python3.12/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science' instead of '\"/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science\"' if you require traitlets >=5.\n",
      "\u001b[1;31m  warn(\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[I 15:13:06.082 NotebookApp] Loading IPython parallel extension\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/home/halil/.local/bin/jupyter-notebook\", line 8, in <module>\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    sys.exit(main())\n",
      "\u001b[1;31m             ^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/jupyter_core/application.py\", line 277, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    app.start()\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 2320, in start\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    success = self._bind_http_server()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1795, in _bind_http_server\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return self._bind_http_server_unix() if self.sock else self._bind_http_server_tcp()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m                                                           ^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1821, in _bind_http_server_tcp\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    self.http_server.listen(port, self.ip)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 191, in listen\n",
      "\u001b[1;31m    self.add_sockets(sockets)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 204, in add_sockets\n",
      "\u001b[1;31m    self._handlers[sock.fileno()] = add_accept_handler(\n",
      "\u001b[1;31m      \n",
      "\u001b[1;31m                              ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/netutil.py\", line 247, in add_accept_handler\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    io_loop = IOLoop.current()\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/ioloop.py\", line 265, in current\n",
      "\u001b[1;31m    loop = asyncio.get_event_loop()\n",
      "\u001b[1;31m           ^^^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/nest_asyncio.py\", line 45, in _get_event_loop\n",
      "\u001b[1;31m    loop = events.get_event_loop_policy().get_event_loop()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/usr/local/lib/python3.12/asyncio/events.py\", line 676, in get_event_loop\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    raise RuntimeError('There is no current event loop in thread %r.'\n",
      "\u001b[1;31mRuntimeError: There is no current event loop in thread 'MainThread'. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "def train_cats(df):\n",
    "    for n,c in df.items():\n",
    "        if is_string_dtype(c):\n",
    "            df[n]=c.astype(\"category\").cat.as_ordered()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mJupyter server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31m/home/halil/.local/lib/python3.12/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science' instead of '\"/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science\"' if you require traitlets >=5.\n",
      "\u001b[1;31m  warn(\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[I 15:13:06.082 NotebookApp] Loading IPython parallel extension\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/home/halil/.local/bin/jupyter-notebook\", line 8, in <module>\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    sys.exit(main())\n",
      "\u001b[1;31m             ^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/jupyter_core/application.py\", line 277, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    app.start()\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 2320, in start\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    success = self._bind_http_server()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1795, in _bind_http_server\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return self._bind_http_server_unix() if self.sock else self._bind_http_server_tcp()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m                                                           ^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1821, in _bind_http_server_tcp\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    self.http_server.listen(port, self.ip)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 191, in listen\n",
      "\u001b[1;31m    self.add_sockets(sockets)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 204, in add_sockets\n",
      "\u001b[1;31m    self._handlers[sock.fileno()] = add_accept_handler(\n",
      "\u001b[1;31m      \n",
      "\u001b[1;31m                              ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/netutil.py\", line 247, in add_accept_handler\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    io_loop = IOLoop.current()\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/ioloop.py\", line 265, in current\n",
      "\u001b[1;31m    loop = asyncio.get_event_loop()\n",
      "\u001b[1;31m           ^^^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/nest_asyncio.py\", line 45, in _get_event_loop\n",
      "\u001b[1;31m    loop = events.get_event_loop_policy().get_event_loop()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/usr/local/lib/python3.12/asyncio/events.py\", line 676, in get_event_loop\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    raise RuntimeError('There is no current event loop in thread %r.'\n",
      "\u001b[1;31mRuntimeError: There is no current event loop in thread 'MainThread'. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "def apply_cats(df,train):\n",
    "    for n,c in df.items():\n",
    "        if train[n].dype == \"category\":\n",
    "            df[n] = pd.Categorical(c,categories = train[n].cat.categories , ordered= True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mJupyter server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31m/home/halil/.local/lib/python3.12/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science' instead of '\"/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science\"' if you require traitlets >=5.\n",
      "\u001b[1;31m  warn(\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[I 15:13:06.082 NotebookApp] Loading IPython parallel extension\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/home/halil/.local/bin/jupyter-notebook\", line 8, in <module>\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    sys.exit(main())\n",
      "\u001b[1;31m             ^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/jupyter_core/application.py\", line 277, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    app.start()\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 2320, in start\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    success = self._bind_http_server()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1795, in _bind_http_server\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return self._bind_http_server_unix() if self.sock else self._bind_http_server_tcp()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m                                                           ^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1821, in _bind_http_server_tcp\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    self.http_server.listen(port, self.ip)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 191, in listen\n",
      "\u001b[1;31m    self.add_sockets(sockets)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 204, in add_sockets\n",
      "\u001b[1;31m    self._handlers[sock.fileno()] = add_accept_handler(\n",
      "\u001b[1;31m      \n",
      "\u001b[1;31m                              ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/netutil.py\", line 247, in add_accept_handler\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    io_loop = IOLoop.current()\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/ioloop.py\", line 265, in current\n",
      "\u001b[1;31m    loop = asyncio.get_event_loop()\n",
      "\u001b[1;31m           ^^^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/nest_asyncio.py\", line 45, in _get_event_loop\n",
      "\u001b[1;31m    loop = events.get_event_loop_policy().get_event_loop()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/usr/local/lib/python3.12/asyncio/events.py\", line 676, in get_event_loop\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    raise RuntimeError('There is no current event loop in thread %r.'\n",
      "\u001b[1;31mRuntimeError: There is no current event loop in thread 'MainThread'. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "train_cats(df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mJupyter server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31m/home/halil/.local/lib/python3.12/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science' instead of '\"/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science\"' if you require traitlets >=5.\n",
      "\u001b[1;31m  warn(\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[I 15:13:06.082 NotebookApp] Loading IPython parallel extension\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/home/halil/.local/bin/jupyter-notebook\", line 8, in <module>\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    sys.exit(main())\n",
      "\u001b[1;31m             ^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/jupyter_core/application.py\", line 277, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    app.start()\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 2320, in start\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    success = self._bind_http_server()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1795, in _bind_http_server\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return self._bind_http_server_unix() if self.sock else self._bind_http_server_tcp()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m                                                           ^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1821, in _bind_http_server_tcp\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    self.http_server.listen(port, self.ip)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 191, in listen\n",
      "\u001b[1;31m    self.add_sockets(sockets)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 204, in add_sockets\n",
      "\u001b[1;31m    self._handlers[sock.fileno()] = add_accept_handler(\n",
      "\u001b[1;31m      \n",
      "\u001b[1;31m                              ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/netutil.py\", line 247, in add_accept_handler\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    io_loop = IOLoop.current()\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/ioloop.py\", line 265, in current\n",
      "\u001b[1;31m    loop = asyncio.get_event_loop()\n",
      "\u001b[1;31m           ^^^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/nest_asyncio.py\", line 45, in _get_event_loop\n",
      "\u001b[1;31m    loop = events.get_event_loop_policy().get_event_loop()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/usr/local/lib/python3.12/asyncio/events.py\", line 676, in get_event_loop\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    raise RuntimeError('There is no current event loop in thread %r.'\n",
      "\u001b[1;31mRuntimeError: There is no current event loop in thread 'MainThread'. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "df[\"UsageBand\"]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mJupyter server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31m/home/halil/.local/lib/python3.12/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science' instead of '\"/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science\"' if you require traitlets >=5.\n",
      "\u001b[1;31m  warn(\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[I 15:13:06.082 NotebookApp] Loading IPython parallel extension\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/home/halil/.local/bin/jupyter-notebook\", line 8, in <module>\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    sys.exit(main())\n",
      "\u001b[1;31m             ^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/jupyter_core/application.py\", line 277, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    app.start()\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 2320, in start\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    success = self._bind_http_server()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1795, in _bind_http_server\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return self._bind_http_server_unix() if self.sock else self._bind_http_server_tcp()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m                                                           ^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1821, in _bind_http_server_tcp\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    self.http_server.listen(port, self.ip)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 191, in listen\n",
      "\u001b[1;31m    self.add_sockets(sockets)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 204, in add_sockets\n",
      "\u001b[1;31m    self._handlers[sock.fileno()] = add_accept_handler(\n",
      "\u001b[1;31m      \n",
      "\u001b[1;31m                              ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/netutil.py\", line 247, in add_accept_handler\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    io_loop = IOLoop.current()\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/ioloop.py\", line 265, in current\n",
      "\u001b[1;31m    loop = asyncio.get_event_loop()\n",
      "\u001b[1;31m           ^^^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/nest_asyncio.py\", line 45, in _get_event_loop\n",
      "\u001b[1;31m    loop = events.get_event_loop_policy().get_event_loop()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/usr/local/lib/python3.12/asyncio/events.py\", line 676, in get_event_loop\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    raise RuntimeError('There is no current event loop in thread %r.'\n",
      "\u001b[1;31mRuntimeError: There is no current event loop in thread 'MainThread'. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "df[\"UsageBand\"].cat.categories"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mJupyter server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31m/home/halil/.local/lib/python3.12/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science' instead of '\"/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science\"' if you require traitlets >=5.\n",
      "\u001b[1;31m  warn(\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[I 15:13:06.082 NotebookApp] Loading IPython parallel extension\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/home/halil/.local/bin/jupyter-notebook\", line 8, in <module>\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    sys.exit(main())\n",
      "\u001b[1;31m             ^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/jupyter_core/application.py\", line 277, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    app.start()\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 2320, in start\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    success = self._bind_http_server()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1795, in _bind_http_server\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return self._bind_http_server_unix() if self.sock else self._bind_http_server_tcp()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m                                                           ^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1821, in _bind_http_server_tcp\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    self.http_server.listen(port, self.ip)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 191, in listen\n",
      "\u001b[1;31m    self.add_sockets(sockets)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 204, in add_sockets\n",
      "\u001b[1;31m    self._handlers[sock.fileno()] = add_accept_handler(\n",
      "\u001b[1;31m      \n",
      "\u001b[1;31m                              ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/netutil.py\", line 247, in add_accept_handler\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    io_loop = IOLoop.current()\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/ioloop.py\", line 265, in current\n",
      "\u001b[1;31m    loop = asyncio.get_event_loop()\n",
      "\u001b[1;31m           ^^^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/nest_asyncio.py\", line 45, in _get_event_loop\n",
      "\u001b[1;31m    loop = events.get_event_loop_policy().get_event_loop()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/usr/local/lib/python3.12/asyncio/events.py\", line 676, in get_event_loop\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    raise RuntimeError('There is no current event loop in thread %r.'\n",
      "\u001b[1;31mRuntimeError: There is no current event loop in thread 'MainThread'. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "df[\"UsageBand\"].cat.set_categories([\"High\",\"Medium\",\"Low\"],ordered=True,inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mJupyter server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31m/home/halil/.local/lib/python3.12/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science' instead of '\"/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science\"' if you require traitlets >=5.\n",
      "\u001b[1;31m  warn(\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[I 15:13:06.082 NotebookApp] Loading IPython parallel extension\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/home/halil/.local/bin/jupyter-notebook\", line 8, in <module>\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    sys.exit(main())\n",
      "\u001b[1;31m             ^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/jupyter_core/application.py\", line 277, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    app.start()\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 2320, in start\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    success = self._bind_http_server()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1795, in _bind_http_server\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return self._bind_http_server_unix() if self.sock else self._bind_http_server_tcp()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m                                                           ^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1821, in _bind_http_server_tcp\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    self.http_server.listen(port, self.ip)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 191, in listen\n",
      "\u001b[1;31m    self.add_sockets(sockets)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 204, in add_sockets\n",
      "\u001b[1;31m    self._handlers[sock.fileno()] = add_accept_handler(\n",
      "\u001b[1;31m      \n",
      "\u001b[1;31m                              ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/netutil.py\", line 247, in add_accept_handler\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    io_loop = IOLoop.current()\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/ioloop.py\", line 265, in current\n",
      "\u001b[1;31m    loop = asyncio.get_event_loop()\n",
      "\u001b[1;31m           ^^^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/nest_asyncio.py\", line 45, in _get_event_loop\n",
      "\u001b[1;31m    loop = events.get_event_loop_policy().get_event_loop()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/usr/local/lib/python3.12/asyncio/events.py\", line 676, in get_event_loop\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    raise RuntimeError('There is no current event loop in thread %r.'\n",
      "\u001b[1;31mRuntimeError: There is no current event loop in thread 'MainThread'. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "df[\"UsageBand\"].cat.categories"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mJupyter server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31m/home/halil/.local/lib/python3.12/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science' instead of '\"/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science\"' if you require traitlets >=5.\n",
      "\u001b[1;31m  warn(\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[I 15:13:06.082 NotebookApp] Loading IPython parallel extension\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/home/halil/.local/bin/jupyter-notebook\", line 8, in <module>\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    sys.exit(main())\n",
      "\u001b[1;31m             ^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/jupyter_core/application.py\", line 277, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    app.start()\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 2320, in start\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    success = self._bind_http_server()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1795, in _bind_http_server\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return self._bind_http_server_unix() if self.sock else self._bind_http_server_tcp()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m                                                           ^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1821, in _bind_http_server_tcp\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    self.http_server.listen(port, self.ip)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 191, in listen\n",
      "\u001b[1;31m    self.add_sockets(sockets)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 204, in add_sockets\n",
      "\u001b[1;31m    self._handlers[sock.fileno()] = add_accept_handler(\n",
      "\u001b[1;31m      \n",
      "\u001b[1;31m                              ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/netutil.py\", line 247, in add_accept_handler\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    io_loop = IOLoop.current()\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/ioloop.py\", line 265, in current\n",
      "\u001b[1;31m    loop = asyncio.get_event_loop()\n",
      "\u001b[1;31m           ^^^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/nest_asyncio.py\", line 45, in _get_event_loop\n",
      "\u001b[1;31m    loop = events.get_event_loop_policy().get_event_loop()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/usr/local/lib/python3.12/asyncio/events.py\", line 676, in get_event_loop\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    raise RuntimeError('There is no current event loop in thread %r.'\n",
      "\u001b[1;31mRuntimeError: There is no current event loop in thread 'MainThread'. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "df[\"UsageBand\"].cat.codes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mJupyter server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31m/home/halil/.local/lib/python3.12/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science' instead of '\"/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science\"' if you require traitlets >=5.\n",
      "\u001b[1;31m  warn(\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[I 15:13:06.082 NotebookApp] Loading IPython parallel extension\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/home/halil/.local/bin/jupyter-notebook\", line 8, in <module>\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    sys.exit(main())\n",
      "\u001b[1;31m             ^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/jupyter_core/application.py\", line 277, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    app.start()\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 2320, in start\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    success = self._bind_http_server()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1795, in _bind_http_server\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return self._bind_http_server_unix() if self.sock else self._bind_http_server_tcp()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m                                                           ^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1821, in _bind_http_server_tcp\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    self.http_server.listen(port, self.ip)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 191, in listen\n",
      "\u001b[1;31m    self.add_sockets(sockets)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 204, in add_sockets\n",
      "\u001b[1;31m    self._handlers[sock.fileno()] = add_accept_handler(\n",
      "\u001b[1;31m      \n",
      "\u001b[1;31m                              ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/netutil.py\", line 247, in add_accept_handler\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    io_loop = IOLoop.current()\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/ioloop.py\", line 265, in current\n",
      "\u001b[1;31m    loop = asyncio.get_event_loop()\n",
      "\u001b[1;31m           ^^^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/nest_asyncio.py\", line 45, in _get_event_loop\n",
      "\u001b[1;31m    loop = events.get_event_loop_policy().get_event_loop()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/usr/local/lib/python3.12/asyncio/events.py\", line 676, in get_event_loop\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    raise RuntimeError('There is no current event loop in thread %r.'\n",
      "\u001b[1;31mRuntimeError: There is no current event loop in thread 'MainThread'. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "def numericalize(df,col,name):\n",
    "    if not is_numeric_dtype(col):\n",
    "        df[name]=col.cat.codes+1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mJupyter server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31m/home/halil/.local/lib/python3.12/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science' instead of '\"/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science\"' if you require traitlets >=5.\n",
      "\u001b[1;31m  warn(\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[I 15:13:06.082 NotebookApp] Loading IPython parallel extension\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/home/halil/.local/bin/jupyter-notebook\", line 8, in <module>\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    sys.exit(main())\n",
      "\u001b[1;31m             ^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/jupyter_core/application.py\", line 277, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    app.start()\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 2320, in start\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    success = self._bind_http_server()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1795, in _bind_http_server\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return self._bind_http_server_unix() if self.sock else self._bind_http_server_tcp()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m                                                           ^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1821, in _bind_http_server_tcp\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    self.http_server.listen(port, self.ip)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 191, in listen\n",
      "\u001b[1;31m    self.add_sockets(sockets)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 204, in add_sockets\n",
      "\u001b[1;31m    self._handlers[sock.fileno()] = add_accept_handler(\n",
      "\u001b[1;31m      \n",
      "\u001b[1;31m                              ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/netutil.py\", line 247, in add_accept_handler\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    io_loop = IOLoop.current()\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/ioloop.py\", line 265, in current\n",
      "\u001b[1;31m    loop = asyncio.get_event_loop()\n",
      "\u001b[1;31m           ^^^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/nest_asyncio.py\", line 45, in _get_event_loop\n",
      "\u001b[1;31m    loop = events.get_event_loop_policy().get_event_loop()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/usr/local/lib/python3.12/asyncio/events.py\", line 676, in get_event_loop\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    raise RuntimeError('There is no current event loop in thread %r.'\n",
      "\u001b[1;31mRuntimeError: There is no current event loop in thread 'MainThread'. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "numericalize(df,df[\"UsageBand\"],\"UsageBand\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mJupyter server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31m/home/halil/.local/lib/python3.12/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science' instead of '\"/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science\"' if you require traitlets >=5.\n",
      "\u001b[1;31m  warn(\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[I 15:13:06.082 NotebookApp] Loading IPython parallel extension\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/home/halil/.local/bin/jupyter-notebook\", line 8, in <module>\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    sys.exit(main())\n",
      "\u001b[1;31m             ^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/jupyter_core/application.py\", line 277, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    app.start()\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 2320, in start\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    success = self._bind_http_server()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1795, in _bind_http_server\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return self._bind_http_server_unix() if self.sock else self._bind_http_server_tcp()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m                                                           ^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1821, in _bind_http_server_tcp\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    self.http_server.listen(port, self.ip)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 191, in listen\n",
      "\u001b[1;31m    self.add_sockets(sockets)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 204, in add_sockets\n",
      "\u001b[1;31m    self._handlers[sock.fileno()] = add_accept_handler(\n",
      "\u001b[1;31m      \n",
      "\u001b[1;31m                              ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/netutil.py\", line 247, in add_accept_handler\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    io_loop = IOLoop.current()\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/ioloop.py\", line 265, in current\n",
      "\u001b[1;31m    loop = asyncio.get_event_loop()\n",
      "\u001b[1;31m           ^^^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/nest_asyncio.py\", line 45, in _get_event_loop\n",
      "\u001b[1;31m    loop = events.get_event_loop_policy().get_event_loop()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/usr/local/lib/python3.12/asyncio/events.py\", line 676, in get_event_loop\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    raise RuntimeError('There is no current event loop in thread %r.'\n",
      "\u001b[1;31mRuntimeError: There is no current event loop in thread 'MainThread'. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "df[\"UsageBand\"]"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Datatime Column"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mJupyter server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31m/home/halil/.local/lib/python3.12/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science' instead of '\"/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science\"' if you require traitlets >=5.\n",
      "\u001b[1;31m  warn(\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[I 15:13:06.082 NotebookApp] Loading IPython parallel extension\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/home/halil/.local/bin/jupyter-notebook\", line 8, in <module>\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    sys.exit(main())\n",
      "\u001b[1;31m             ^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/jupyter_core/application.py\", line 277, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    app.start()\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 2320, in start\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    success = self._bind_http_server()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1795, in _bind_http_server\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return self._bind_http_server_unix() if self.sock else self._bind_http_server_tcp()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m                                                           ^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1821, in _bind_http_server_tcp\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    self.http_server.listen(port, self.ip)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 191, in listen\n",
      "\u001b[1;31m    self.add_sockets(sockets)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 204, in add_sockets\n",
      "\u001b[1;31m    self._handlers[sock.fileno()] = add_accept_handler(\n",
      "\u001b[1;31m      \n",
      "\u001b[1;31m                              ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/netutil.py\", line 247, in add_accept_handler\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    io_loop = IOLoop.current()\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/ioloop.py\", line 265, in current\n",
      "\u001b[1;31m    loop = asyncio.get_event_loop()\n",
      "\u001b[1;31m           ^^^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/nest_asyncio.py\", line 45, in _get_event_loop\n",
      "\u001b[1;31m    loop = events.get_event_loop_policy().get_event_loop()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/usr/local/lib/python3.12/asyncio/events.py\", line 676, in get_event_loop\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    raise RuntimeError('There is no current event loop in thread %r.'\n",
      "\u001b[1;31mRuntimeError: There is no current event loop in thread 'MainThread'. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "df[\"saledate\"]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mJupyter server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31m/home/halil/.local/lib/python3.12/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science' instead of '\"/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science\"' if you require traitlets >=5.\n",
      "\u001b[1;31m  warn(\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[I 15:13:06.082 NotebookApp] Loading IPython parallel extension\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/home/halil/.local/bin/jupyter-notebook\", line 8, in <module>\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    sys.exit(main())\n",
      "\u001b[1;31m             ^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/jupyter_core/application.py\", line 277, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    app.start()\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 2320, in start\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    success = self._bind_http_server()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1795, in _bind_http_server\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return self._bind_http_server_unix() if self.sock else self._bind_http_server_tcp()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m                                                           ^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1821, in _bind_http_server_tcp\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    self.http_server.listen(port, self.ip)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 191, in listen\n",
      "\u001b[1;31m    self.add_sockets(sockets)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 204, in add_sockets\n",
      "\u001b[1;31m    self._handlers[sock.fileno()] = add_accept_handler(\n",
      "\u001b[1;31m      \n",
      "\u001b[1;31m                              ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/netutil.py\", line 247, in add_accept_handler\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    io_loop = IOLoop.current()\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/ioloop.py\", line 265, in current\n",
      "\u001b[1;31m    loop = asyncio.get_event_loop()\n",
      "\u001b[1;31m           ^^^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/nest_asyncio.py\", line 45, in _get_event_loop\n",
      "\u001b[1;31m    loop = events.get_event_loop_policy().get_event_loop()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/usr/local/lib/python3.12/asyncio/events.py\", line 676, in get_event_loop\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    raise RuntimeError('There is no current event loop in thread %r.'\n",
      "\u001b[1;31mRuntimeError: There is no current event loop in thread 'MainThread'. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "df[\"saledate\"].year"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mJupyter server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31m/home/halil/.local/lib/python3.12/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science' instead of '\"/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science\"' if you require traitlets >=5.\n",
      "\u001b[1;31m  warn(\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[I 15:13:06.082 NotebookApp] Loading IPython parallel extension\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/home/halil/.local/bin/jupyter-notebook\", line 8, in <module>\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    sys.exit(main())\n",
      "\u001b[1;31m             ^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/jupyter_core/application.py\", line 277, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    app.start()\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 2320, in start\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    success = self._bind_http_server()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1795, in _bind_http_server\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return self._bind_http_server_unix() if self.sock else self._bind_http_server_tcp()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m                                                           ^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1821, in _bind_http_server_tcp\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    self.http_server.listen(port, self.ip)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 191, in listen\n",
      "\u001b[1;31m    self.add_sockets(sockets)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 204, in add_sockets\n",
      "\u001b[1;31m    self._handlers[sock.fileno()] = add_accept_handler(\n",
      "\u001b[1;31m      \n",
      "\u001b[1;31m                              ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/netutil.py\", line 247, in add_accept_handler\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    io_loop = IOLoop.current()\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/ioloop.py\", line 265, in current\n",
      "\u001b[1;31m    loop = asyncio.get_event_loop()\n",
      "\u001b[1;31m           ^^^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/nest_asyncio.py\", line 45, in _get_event_loop\n",
      "\u001b[1;31m    loop = events.get_event_loop_policy().get_event_loop()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/usr/local/lib/python3.12/asyncio/events.py\", line 676, in get_event_loop\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    raise RuntimeError('There is no current event loop in thread %r.'\n",
      "\u001b[1;31mRuntimeError: There is no current event loop in thread 'MainThread'. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "df[\"saledate\"].dt.year"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mJupyter server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31m/home/halil/.local/lib/python3.12/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science' instead of '\"/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science\"' if you require traitlets >=5.\n",
      "\u001b[1;31m  warn(\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[I 15:13:06.082 NotebookApp] Loading IPython parallel extension\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/home/halil/.local/bin/jupyter-notebook\", line 8, in <module>\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    sys.exit(main())\n",
      "\u001b[1;31m             ^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/jupyter_core/application.py\", line 277, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    app.start()\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 2320, in start\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    success = self._bind_http_server()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1795, in _bind_http_server\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return self._bind_http_server_unix() if self.sock else self._bind_http_server_tcp()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m                                                           ^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1821, in _bind_http_server_tcp\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    self.http_server.listen(port, self.ip)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 191, in listen\n",
      "\u001b[1;31m    self.add_sockets(sockets)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 204, in add_sockets\n",
      "\u001b[1;31m    self._handlers[sock.fileno()] = add_accept_handler(\n",
      "\u001b[1;31m      \n",
      "\u001b[1;31m                              ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/netutil.py\", line 247, in add_accept_handler\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    io_loop = IOLoop.current()\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/ioloop.py\", line 265, in current\n",
      "\u001b[1;31m    loop = asyncio.get_event_loop()\n",
      "\u001b[1;31m           ^^^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/nest_asyncio.py\", line 45, in _get_event_loop\n",
      "\u001b[1;31m    loop = events.get_event_loop_policy().get_event_loop()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/usr/local/lib/python3.12/asyncio/events.py\", line 676, in get_event_loop\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    raise RuntimeError('There is no current event loop in thread %r.'\n",
      "\u001b[1;31mRuntimeError: There is no current event loop in thread 'MainThread'. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "\"hey\".capitalize()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "\u001b[1;31mJupyter server crashed. Unable to connect. \n",
      "\u001b[1;31mError code from Jupyter: 1\n",
      "\u001b[1;31m/home/halil/.local/lib/python3.12/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science' instead of '\"/home/halil/Belgeler/Kodlama calismalari/py/Patika/Intermadiate data science\"' if you require traitlets >=5.\n",
      "\u001b[1;31m  warn(\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m[I 15:13:06.082 NotebookApp] Loading IPython parallel extension\n",
      "\u001b[1;31m\n",
      "\u001b[1;31mTraceback (most recent call last):\n",
      "\u001b[1;31m  File \"/home/halil/.local/bin/jupyter-notebook\", line 8, in <module>\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    sys.exit(main())\n",
      "\u001b[1;31m             ^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/jupyter_core/application.py\", line 277, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return super().launch_instance(argv=argv, **kwargs)\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    app.start()\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 2320, in start\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    success = self._bind_http_server()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1795, in _bind_http_server\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    return self._bind_http_server_unix() if self.sock else self._bind_http_server_tcp()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m                                                           ^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/notebook/notebookapp.py\", line 1821, in _bind_http_server_tcp\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    self.http_server.listen(port, self.ip)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 191, in listen\n",
      "\u001b[1;31m    self.add_sockets(sockets)\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/tcpserver.py\", line 204, in add_sockets\n",
      "\u001b[1;31m    self._handlers[sock.fileno()] = add_accept_handler(\n",
      "\u001b[1;31m      \n",
      "\u001b[1;31m                              ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/netutil.py\", line 247, in add_accept_handler\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    io_loop = IOLoop.current()\n",
      "\u001b[1;31m              ^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/tornado/ioloop.py\", line 265, in current\n",
      "\u001b[1;31m    loop = asyncio.get_event_loop()\n",
      "\u001b[1;31m           ^^^^\n",
      "\u001b[1;31m^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/home/halil/.local/lib/python3.12/site-packages/nest_asyncio.py\", line 45, in _get_event_loop\n",
      "\u001b[1;31m    loop = events.get_event_loop_policy().get_event_loop()\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[1;31m  File \"/usr/local/lib/python3.12/asyncio/events.py\", line 676, in get_event_loop\n",
      "\u001b[1;31m\n",
      "\u001b[1;31m    raise RuntimeError('There is no current event loop in thread %r.'\n",
      "\u001b[1;31mRuntimeError: There is no current event loop in thread 'MainThread'. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.9.16"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "b628485bec5cdac3dc960cdf2a71ce67507a7bc0e67d623b9220b6c93af93181"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
